name: Build
  
on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Maven Package gateway
        run: mvn -f ./BankPrototype/gateway/pom.xml -B clean package -DskipTests
      - name: Maven Package application
        run: mvn -f ./BankPrototype/application/pom.xml -B clean package -DskipTests
      - name: Maven Package deal
        run: mvn -f ./BankPrototype/deal/pom.xml -B clean package -DskipTests
      - name: Maven Package dossier
        run: mvn -f ./BankPrototype/dossier/pom.xml -B clean package -DskipTests
      - name: Maven Package credit-conveyor
        run: mvn -f ./BankPrototype/credit-conveyor/pom.xml -B clean package -DskipTests
