name: SonarCloud

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarCloud1:
    name: SonarCloudDeal
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v1
        - name: SonarCloud Scan
          uses: actions/setup-java@v1
          with:
            java-version: '11'
        - name: Analyze with SonarCloud
          run: mvn -f ./BankPrototype/deal/ -B verify sonar:sonar -Dsonar.projectKey=Gyrf921_Bank-Prototype -Dsonar.organization=gyrf921 -Dsonar.host.url=https://sonarcloud.io -Dsonar.token=$SONAR_TOKEN
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  sonarCloud2:
    name: SonarCloudApplication
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v1
        - name: SonarCloud Scan
          uses: actions/setup-java@v1
          with:
            java-version: '11'
        - name: Analyze with SonarCloud
          run: ./mvnw -f ./BankPrototype/application/ -B verify sonar:sonar -Dsonar.projectKey=Gyrf921_Bank-Prototype -Dsonar.organization=gyrf921 -Dsonar.host.url=https://sonarcloud.io -Dsonar.token=$SONAR_TOKEN
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          
  sonarCloud3:
    name: SonarCloud3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: BankPrototype/gateway/
          
  sonarCloud4:
    name: SonarCloud4
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: BankPrototype/dossier/

  sonarCloud5:
    name: SonarCloud5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: BankPrototype/application/
